export default {
  UPDATE_ONE_SHOT: 'update-one-shot',
  UPDATE_BONUS: 'update-bonus',
  UPDATE_PLAYER_NAME: 'update-player-name',
  UPDATE_NAME: 'update-name',
  UPDATE_RACE: 'update-race',
  UPDATE_FACTION: 'update-faction',
  UPDATE_CLASS: 'update-class',
  UPDATE_SUBCLASS: 'update-subclass',
  UPDATE_RELIGION: 'update-religion',
  UPDATE_LANGUAGE_CATEGORY: 'update-language-category',
  UPDATE_LANGUAGE: 'update-language',
  UPDATE_ATTRIBUTES: 'update-attributes',
  UPDATE_SUBATTRIBUTES: 'update-subattributes',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
  // UPDATE_: 'update-',
};
